name: iOS

on:
  push:
    branches:
      - main
      - cli
  workflow_dispatch:
    branches:
      - main
      - cli

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.0
    - run: npm ci
    - run: xcode-select -p
    - run: pod install
      working-directory: ios
      name: Install pod dependencies
    - run: pwd
      name: show path
    - run: mkdir my_build_dir && cd my_build_dir && touch test_file.txt && pwd
      name: create build dir
    - run: pwd
      name: show path again  
    - run: npx react-native run-ios --configuration Release
      name: Build with cli
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: IOSTest
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphonesimulator/IOSTest.app
