name: iOS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.0
    - run: npm ci
    - run: xcode-select -p
    - run: pod install
      working-directory: ios
      name: Install pod dependencies
        
    - name: Build app
      run: |
          xcodebuild -workspace ios/IOSTest.xcworkspace -scheme IOSTest archive -archivePath IOSTest.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./IOSTest.xcarchive -exportPath . -exportOptionsPlist IOSTest/Info.plist
          mv IOSTest.ipa ../IOSTest.ipa
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: debug_build
        path: ios/build/
