name: iOS

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.0
    - run: npm ci
    - run: xcode-select -p
    - run: pod install
      working-directory: ios
      name: Install pod dependencies
    - name: Build iOS (debug)
      run: "xcodebuild \
        -workspace ios/IOSTest.xcworkspace \
        -scheme IOSTest \
        clean archive \
        -sdk iphoneos \
        -configuration Debug \
        -UseModernBuildSystem=YES \
        CODE_SIGNING_ALLOWED=NO"
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: IOSTest
        path: ~/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
