name: iOS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.0
    - run: npm ci
    - run: xcode-select -p
    - run: pod install
      working-directory: ios
      name: Install pod dependencies
    
    - name: Build
      run: "xcodebuild \
        clean \
        -project ios/IOSTest.xcodeproj \
        -configuration Debug 
        -alltargets"
        
    - name: Archive
      run: "xcodebuild \
        archive \
        -project ios/IOSTest.xcodeproj \
        -scheme ios/IOSTest \
        -archivePath ios/IOSTest.xcarchive"
        
    - name: Export iOS
      run: "xcodebuild \
        -exportArchive \
        -archivePath ios/IOSTest.xcarchive \
        -exportPath my_export_dir \
        -exportFormat ipa \
        -exportProvisioningProfile 'NameProvision'"
    
#     - name: Upload Artifact
#       uses: actions/upload-artifact@v1
#       with:
#         name: IOSTest
#         path: my_export_dir/
