name: iOS

on: workflow_dispatch
    

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v2
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: yarn install --frozen-lockfile

      - run: pod install
        working-directory: ios

      - run: xcodebuild clean archive -workspace IOSTest.xcworkspace -scheme testCiCdReactNative -archivePath IOSTest.xcarchive CODE_SIGNING_ALLOWED=NO | xcpretty
        working-directory: ios
